### ISSUE TITLE
An API Documentation for DX Auth 

### ISSUE THREAD

**Issue by eyoosuf** [eyoosuf/DX-Auth#3]
A detailed documentation about the DX auth would help Developers/New Developers to use the library easily

**Comment by Eng3nhoc4s** [comment]
Hi, is it possible to provide a registration free way of getting the documentation of DX_Auth in .pdf format?

Thanks =)

**Comment by rfulcher** [comment]
I have a copy of the old documentation if anyone wants it.

**Comment by thompcha** [comment]
@rfulcher Yes, please!

**Comment by rfulcher** [comment]
what is the best way to get it to you?

On Wed, Jun 10, 2015 at 12:10 PM, thompcha <notifications@github.com> wrote:

> @rfulcher <https://github.com/rfulcher> Yes, please!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eyoosuf/DX-Auth/issues/3#issuecomment-110814955>.
>



-- 
Robert Fulcher
iWAT LLC
Phone: 717-884-9281
Cell: 717-658-5100
rob@iwatllc.com
www.iwatllc.com

___/Confidentiality Notice\_____________________________
This email message, including any attachments, is for the sole use of
intended recipient(s) and may contain confidential and privileged
information. Any unauthorized review, use, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply email and destroy all copies of the original message.

**Comment by thompcha** [comment]
By email please! charliet@gmail.com

**Comment by Eng3nhoc4s** [comment]
You could use any other uploading system like Mega or Dropbox, or simply upload the pdf to the same level as your readme.md =)

**Comment by rfulcher** [comment]
I don't think I have access to upload to the readme

On Wed, Jun 10, 2015 at 4:50 PM, Rodrigo Reis <notifications@github.com>
wrote:

> You could use any other uploading system like Mega or Dropbox, or simply
> upload the pdf to the same level as your readme.md =)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eyoosuf/DX-Auth/issues/3#issuecomment-110908822>.
>



-- 
Robert Fulcher
iWAT LLC
Phone: 717-884-9281
Cell: 717-658-5100
rob@iwatllc.com
www.iwatllc.com

___/Confidentiality Notice\_____________________________
This email message, including any attachments, is for the sole use of
intended recipient(s) and may contain confidential and privileged
information. Any unauthorized review, use, disclosure or distribution is
prohibited. If you are not the intended recipient, please contact the
sender by reply email and destroy all copies of the original message.

**Comment by eyoosuf** [comment]
@rfulcher do the changes and send a pull request
