### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by everlon** [eyoosuf/DX-Auth#6]
This library is in need of attention. Need to do some updates. Is expected?

**Comment by rfulcher** [comment]
I have updated it to CI3 and also added an MSSQL file so that the system will run against MS SQL server.  What other updates would you like to see?

**Comment by rfulcher** [comment]
I have updated my fork to be CI 3.0 in HMVC.  I have fixed a few bugs and upgraded the password hashing to phpass. you can check it out here.

https://github.com/iwatllc/DX-Auth.git

**Comment by eyoosuf** [comment]
@rfulcher  send a pull request please
