### ISSUE TITLE
CI3 registration

### ISSUE THREAD

**Issue by sasu4** [eyoosuf/DX-Auth#9]
Hi,

I'm testing DX-Auth on the newest CI and after registration I get an error about salt (but the registration completes anyway). Thanks for help.

Severity: Notice
Message: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.

Filename: libraries/DX_Auth.php
Line Number: 946
Backtrace:
File: D:\xampp\htdocs\ci3\application\libraries\DX_Auth.php
Line: 946
Function: crypt

File: D:\xampp\htdocs\ci3\application\controllers\Auth.php
Line: 160
Function: register

File: D:\xampp\htdocs\ci3\index.php
Line: 292
Function: require_once

**Comment by rfulcher** [comment]
sasu4,

I just saw your post.  There is a place to specify the salt in the config file line 59

$config['DX_salt'] = '';

This might be causing your issue.

**Comment by sasu4** [comment]
Yep I know about it, I filled there the salt but still get the warning. I found out that it is a warning on the newest php version, the registration completes but it is a little annoying

**Comment by rfulcher** [comment]
I will have to try and replicate the issue.  so once the user registers that is when you get the message?

Thanks

**Comment by sasu4** [comment]
![register](https://cloud.githubusercontent.com/assets/10462129/8088575/97c47dba-0fa2-11e5-9e75-4d9512f430fe.jpg)
I'm running it on XAMPP. Yes I get the message rigth after the registration.

**Comment by zheselevko** [comment]
Fatal error: Call to undefined method DX_Auth::captcha() in C:\wamp\www\cmspro.loc\application\controllers\Auth.php on line 111

**Comment by sasu4** [comment]
zheselevko, I had the same problem if the user didn't login correctly three times and then the captcha didn't loaded... i turned it off :-1:

**Comment by rfulcher** [comment]
sasu4,

Can you give me the setup to reproduce this.  I can't seem to get the error to occur.

Thanks

**Comment by sasu4** [comment]
I forked dx-auth and tried it on default setup, it occured right at first shot. Just input wrong password 3 times in a row when you want to login and you get this:

Fatal error: Call to undefined method DX_Auth::captcha() in D:\xampp\htdocs\DX-Auth\application\controllers\Auth.php on line 111
A PHP Error was encountered
Severity: Error
Message: Call to undefined method DX_Auth::captcha()
Filename: controllers/Auth.php
Line Number: 111
Backtrace:

**Comment by rfulcher** [comment]
I think this issue has been fixed in my fork.

https://github.com/iwatllc/DX-Auth.git

**Comment by eyoosuf** [comment]
@rfulcher send a pull request, it will be useful for others

**Comment by jollin-george** [comment]
Have any one solved 
Severity: Notice
Message: crypt(): No salt parameter was specified. You must use a randomly generated salt and a strong hash function to produce a secure hash.

**Comment by jollin-george** [comment]
Type: Error

Message: Call to a member function HashPassword() on null

Filename: F:\xampp\htdocs\wanderer\application\libraries\DX_Auth.php

Line Number: 180

Backtrace:

File: F:\xampp\htdocs\wanderer\application\libraries\DX_Auth.php
Line: 992
Function: _encode

File: F:\xampp\htdocs\wanderer\application\controllers\Auth.php
Line: 161
Function: register

File: F:\xampp\htdocs\wanderer\index.php
Line: 319
Function: require_once
